string = File.open('pack.in','r'){|f| f.read}
mas = string.split(' ')
a = mas[0].to_f
b = mas[1].to_f
#a = Math.sqrt(l**2+(b/2)**2)
l =Math.sqrt(a**2 - (b/2)**2)
alfa = Math.acos(b/(2*a))
sungl = 2*a*b*Math.cos(alfa)
#puts "S ungle = #{sungl}"
#puts "b = #{b}"
#puts "a  = #{a}"
S = l*b/2 
p = (a + b/2)
puts "S = #{S}"
puts "p = #{p}"
#r = sungl / p
r= S/p
#r = Math.sqrt(2*(p-a)*(p-b)/p)
puts "r = #{r}"
